version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec ./bin/rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/onenote
    ports:
      - "3000:3000"
    links:
      - mailcatcher
    depends_on: 
      - db
  mailcatcher:
    image: zolweb/docker-mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
